### ISSUE TITLE
xenon -v -v -v ssh exec output contains EdDSA provider not supported Java exception

### ISSUE THREAD

**Issue by jspaaks** [xenon-middleware/xenon-cli#26]
I'm seeing the following Java exception in ``xenon --verbose --verbose --verbose ssh exec`` log. Not sure if that's normal. 

```text
org.apache.sshd.common.SshException: EdDSA provider not supported
	at org.apache.sshd.common.util.buffer.Buffer.getRawPublicKey(Buffer.java:400) ~[sshd-core-1.4.0.jar:1.4.0]
	at org.apache.sshd.common.util.buffer.Buffer.getPublicKey(Buffer.java:374) ~[sshd-core-1.4.0.jar:1.4.0]
	at org.apache.sshd.common.global.AbstractOpenSshHostKeysHandler.process(AbstractOpenSshHostKeysHandler.java:70) ~[sshd-core-1.4.0.jar:1.4.0]
	at org.apache.sshd.common.global.AbstractOpenSshHostKeysHandler.process(AbstractOpenSshHostKeysHandler.java:38) ~[sshd-core-1.4.0.jar:1.4.0]
	at org.apache.sshd.common.session.helpers.AbstractConnectionService.globalRequest(AbstractConnectionService.java:645) [sshd-core-1.4.0.jar:1.4.0]
	at org.apache.sshd.common.session.helpers.AbstractConnectionService.process(AbstractConnectionService.java:353) [sshd-core-1.4.0.jar:1.4.0]
	at org.apache.sshd.common.session.helpers.AbstractSession.doHandleMessage(AbstractSession.java:564) [sshd-core-1.4.0.jar:1.4.0]
	at org.apache.sshd.common.session.helpers.AbstractSession.handleMessage(AbstractSession.java:497) [sshd-core-1.4.0.jar:1.4.0]
	at org.apache.sshd.common.session.helpers.AbstractSession.decode(AbstractSession.java:1406) [sshd-core-1.4.0.jar:1.4.0]
	at org.apache.sshd.common.session.helpers.AbstractSession.messageReceived(AbstractSession.java:458) [sshd-core-1.4.0.jar:1.4.0]
	at org.apache.sshd.common.session.helpers.AbstractSessionIoHandler.messageReceived(AbstractSessionIoHandler.java:67) [sshd-core-1.4.0.jar:1.4.0]
	at org.apache.sshd.common.io.nio2.Nio2Session.handleReadCycleCompletion(Nio2Session.java:277) [sshd-core-1.4.0.jar:1.4.0]
	at org.apache.sshd.common.io.nio2.Nio2Session$1.onCompleted(Nio2Session.java:257) [sshd-core-1.4.0.jar:1.4.0]
	at org.apache.sshd.common.io.nio2.Nio2Session$1.onCompleted(Nio2Session.java:254) [sshd-core-1.4.0.jar:1.4.0]
	at org.apache.sshd.common.io.nio2.Nio2CompletionHandler.lambda$completed$0(Nio2CompletionHandler.java:38) [sshd-core-1.4.0.jar:1.4.0]
	at java.security.AccessController.doPrivileged(Native Method) ~[na:1.8.0_131]
	at org.apache.sshd.common.io.nio2.Nio2CompletionHandler.completed(Nio2CompletionHandler.java:37) [sshd-core-1.4.0.jar:1.4.0]
	at sun.nio.ch.Invoker.invokeUnchecked(Invoker.java:126) ~[na:1.8.0_131]
	at sun.nio.ch.Invoker$2.run(Invoker.java:218) ~[na:1.8.0_131]
	at sun.nio.ch.AsynchronousChannelGroupImpl$1.run(AsynchronousChannelGroupImpl.java:112) ~[na:1.8.0_131]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) ~[na:1.8.0_131]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) ~[na:1.8.0_131]
	at java.lang.Thread.run(Thread.java:748) ~[na:1.8.0_131]
Caused by: java.security.NoSuchAlgorithmException: EdDSA provider not supported
	at org.apache.sshd.common.util.security.SecurityUtils.generateEDDSAPublicKey(SecurityUtils.java:594) ~[sshd-core-1.4.0.jar:1.4.0]
	at org.apache.sshd.common.util.buffer.keys.ED25519BufferPublicKeyParser.getRawPublicKey(ED25519BufferPublicKeyParser.java:45) ~[sshd-core-1.4.0.jar:1.4.0]
	at org.apache.sshd.common.util.buffer.keys.BufferPublicKeyParser$2.getRawPublicKey(BufferPublicKeyParser.java:98) ~[sshd-core-1.4.0.jar:1.4.0]
	at org.apache.sshd.common.util.buffer.Buffer.getRawPublicKey(Buffer.java:398) ~[sshd-core-1.4.0.jar:1.4.0]
	... 22 common frames omitted
```

**Comment by sverhoeven** [comment]
By adding eddsa (https://github.com/str4d/ed25519-java) as compile dependency the stack trace is changed into
```
java.lang.NullPointerException: null
	at net.i2p.crypto.eddsa.spec.EdDSAPublicKeySpec.<init>(EdDSAPublicKeySpec.java:33) ~[eddsa-0.2.0.jar:na]
	at org.apache.sshd.common.util.security.eddsa.EdDSASecurityProvider.generateEDDSAPublicKey(EdDSASecurityProvider.java:173) ~[sshd-core-1.4.0.jar:1.4.0]
	at org.apache.sshd.common.util.security.SecurityUtils.generateEDDSAPublicKey(SecurityUtils.java:597) ~[sshd-core-1.4.0.jar:1.4.0]
	at org.apache.sshd.common.util.buffer.keys.ED25519BufferPublicKeyParser.getRawPublicKey(ED25519BufferPublicKeyParser.java:45) ~[sshd-core-1.4.0.jar:1.4.0]
	at org.apache.sshd.common.util.buffer.keys.BufferPublicKeyParser$2.getRawPublicKey(BufferPublicKeyParser.java:98) ~[sshd-core-1.4.0.jar:1.4.0]
	at org.apache.sshd.common.util.buffer.Buffer.getRawPublicKey(Buffer.java:398) ~[sshd-core-1.4.0.jar:1.4.0]
	at org.apache.sshd.common.util.buffer.Buffer.getPublicKey(Buffer.java:374) ~[sshd-core-1.4.0.jar:1.4.0]
	at org.apache.sshd.common.global.AbstractOpenSshHostKeysHandler.process(AbstractOpenSshHostKeysHandler.java:70) ~[sshd-core-1.4.0.jar:1.4.0]
	at org.apache.sshd.common.global.AbstractOpenSshHostKeysHandler.process(AbstractOpenSshHostKeysHandler.java:38) ~[sshd-core-1.4.0.jar:1.4.0]
	at org.apache.sshd.common.session.helpers.AbstractConnectionService.globalRequest(AbstractConnectionService.java:645) [sshd-core-1.4.0.jar:1.4.0]
	at org.apache.sshd.common.session.helpers.AbstractConnectionService.process(AbstractConnectionService.java:353) [sshd-core-1.4.0.jar:1.4.0]
	at org.apache.sshd.common.session.helpers.AbstractSession.doHandleMessage(AbstractSession.java:564) [sshd-core-1.4.0.jar:1.4.0]
	at org.apache.sshd.common.session.helpers.AbstractSession.handleMessage(AbstractSession.java:497) [sshd-core-1.4.0.jar:1.4.0]
	at org.apache.sshd.common.session.helpers.AbstractSession.decode(AbstractSession.java:1406) [sshd-core-1.4.0.jar:1.4.0]
	at org.apache.sshd.common.session.helpers.AbstractSession.messageReceived(AbstractSession.java:458) [sshd-core-1.4.0.jar:1.4.0]
	at org.apache.sshd.common.session.helpers.AbstractSessionIoHandler.messageReceived(AbstractSessionIoHandler.java:67) [sshd-core-1.4.0.jar:1.4.0]
	at org.apache.sshd.common.io.nio2.Nio2Session.handleReadCycleCompletion(Nio2Session.java:277) [sshd-core-1.4.0.jar:1.4.0]
	at org.apache.sshd.common.io.nio2.Nio2Session$1.onCompleted(Nio2Session.java:257) [sshd-core-1.4.0.jar:1.4.0]
	at org.apache.sshd.common.io.nio2.Nio2Session$1.onCompleted(Nio2Session.java:254) [sshd-core-1.4.0.jar:1.4.0]
	at org.apache.sshd.common.io.nio2.Nio2CompletionHandler.lambda$completed$0(Nio2CompletionHandler.java:38) [sshd-core-1.4.0.jar:1.4.0]
	at java.security.AccessController.doPrivileged(Native Method) ~[na:1.8.0_131]
	at org.apache.sshd.common.io.nio2.Nio2CompletionHandler.completed(Nio2CompletionHandler.java:37) [sshd-core-1.4.0.jar:1.4.0]
	at sun.nio.ch.Invoker.invokeUnchecked(Invoker.java:126) ~[na:1.8.0_131]
	at sun.nio.ch.Invoker$2.run(Invoker.java:218) ~[na:1.8.0_131]
	at sun.nio.ch.AsynchronousChannelGroupImpl$1.run(AsynchronousChannelGroupImpl.java:112) ~[na:1.8.0_131]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) ~[na:1.8.0_131]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) ~[na:1.8.0_131]
	at java.lang.Thread.run(Thread.java:748) ~[na:1.8.0_131]

```

**Comment by sverhoeven** [comment]
Support for ssh-ed25519 keys and ed25519-sha-512 signatures has been added to Xenon, see
https://github.com/xenon-middleware/xenon/blob/ce25614c6e0bd5f9aa4be76584293343ee4440ac/build.gradle#L60

Unable to reproduce error anymore using latest xenon-cli with
```sh
mv ~/.ssh ~/.ssh.xenon-error
ssh-keygen -t ed25519
docker run --detach --publish 10022:22 nlesc/xenon-ssh
# Setup passwordless loging
ssh-copy-id -i ~/.ssh/id_ed25519 -p 10022 xenon@localhost
# Test login works passwordless with openssh
ssh -p 10022 xenon@localhost hostname
xenon scheduler ssh --location localhost:10022 --user xenon exec hostname
rm -rf ~/.ssh
mv ~/.ssh.xenon-error ~/.ssh
```
Xenon-cli returns the hostname of the Docker container successfully.
